# Generated by Django 4.2.6 on 2023-12-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('name_language', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Name Language')),
                ('id_country', models.CharField(max_length=3, verbose_name='id country')),
                ('id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language', verbose_name='idLanguageofcountry')),
            ],
            options={
                'verbose_name': 'Name Language',
                'verbose_name_plural': 'Name Languages',
                'ordering': ['name_language'],
                'unique_together': {('id_language', 'id_country')},
            },
        ),
    ]
